In [ ]:
# importing the neccessary libraries 

import numpy as np
import pandas as pd
import sklearn
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [ ]:
# let's load the dataset into the dataframe 

df = pd.read_csv(r"insuranceFraud.csv")


In [ ]:
df.head()

In [ ]:
df.info()

In [ ]:
df.describe()

## EDA 

In [15]:
#let's check for duplicate values 
df.duplicated().sum()

0

In [ ]:
# let's check the null values
df.isna().sum()

In [ ]:
# There are only 91 values that are missing in the 'authorities contacted column', since it is a categorical column , we will remove this feature from our dataset
df = df.drop('authorities_contacted',axis=1)

In [ ]:
df.isna().sum()

In [ ]:
import plotly.express as px

In [ ]:
# Let's count the classes of the dependent variable 
count_classes = pd.value_counts(df['fraud_reported'], sort= True)

# Let's now visylize the count_classes

fig = px.bar(count_classes, x= count_classes.index, y= count_classes.values)

fig.update_layout(xaxis=dict(
    tickvals=[0, 1],
    ticktext=["Normal", "Fraud"]
), 
title = "Class Distribution",
yaxis_title="Frequency"
)
fig.show()
                  

In [19]:
column_names = df.columns.tolist()


In [22]:
df.head()

months_as_customer  age  policy_number policy_bind_date policy_state  \
0                 328   48         521585       10/17/2014           OH   
1                 228   42         342868        6/27/2006           IN   
2                 134   29         687698         9/6/2000           OH   
3                 256   41         227811        5/25/1990           IL   
4                 228   44         367455         6/6/2014           IL   

  policy_csl  policy_deductable  policy_annual_premium  umbrella_limit  \
0    250/500               1000                1406.91               0   
1    250/500               2000                1197.22         5000000   
2    100/300               2000                1413.14         5000000   
3    250/500               2000                1415.74         6000000   
4   500/1000               1000                1583.91         6000000   

   insured_zip  ... witnesses police_report_available total_claim_amount  \
0       466132  ...         2                     YES              71610   
1       468176  ...         0                       ?               5070   
2       430632  ...         3                      NO              34650   
3       608117  ...         2                      NO              63400   
4       610706  ...         1                      NO               6500   

  injury_claim property_claim  vehicle_claim  auto_make auto_model auto_year  \
0         6510          13020          52080       Saab        92x      2004   
1          780            780           3510   Mercedes       E400      2007   
2         7700           3850          23100      Dodge        RAM      2007   
3         6340           6340          50720  Chevrolet      Tahoe      2014   
4         1300            650           4550     Accura        RSX      2009   

  fraud_reported  
0              Y  
1              Y  
2              N  
3              Y  
4              N  

[5 rows x 38 columns]

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 38 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   months_as_customer           1000 non-null   int64  
 1   age                          1000 non-null   int64  
 2   policy_number                1000 non-null   int64  
 3   policy_bind_date             1000 non-null   object 
 4   policy_state                 1000 non-null   object 
 5   policy_csl                   1000 non-null   object 
 6   policy_deductable            1000 non-null   int64  
 7   policy_annual_premium        1000 non-null   float64
 8   umbrella_limit               1000 non-null   int64  
 9   insured_zip                  1000 non-null   int64  
 10  insured_sex                  1000 non-null   object 
 11  insured_education_level      1000 non-null   object 
 12  insured_occupation           1000 non-null   object 
 13  insured_hobbies    

In [20]:
column_names

['months_as_customer',
 'age',
 'policy_number',
 'policy_bind_date',
 'policy_state',
 'policy_csl',
 'policy_deductable',
 'policy_annual_premium',
 'umbrella_limit',
 'insured_zip',
 'insured_sex',
 'insured_education_level',
 'insured_occupation',
 'insured_hobbies',
 'insured_relationship',
 'capital-gains',
 'capital-loss',
 'incident_date',
 'incident_type',
 'collision_type',
 'incident_severity',
 'incident_state',
 'incident_city',
 'incident_location',
 'incident_hour_of_the_day',
 'number_of_vehicles_involved',
 'property_damage',
 'bodily_injuries',
 'witnesses',
 'police_report_available',
 'total_claim_amount',
 'injury_claim',
 'property_claim',
 'vehicle_claim',
 'auto_make',
 'auto_model',
 'auto_year',
 'fraud_reported']

In [23]:
# let's drop the unique policy number and the policy_number column
df = df.drop(['policy_number'],axis=1)

In [24]:
df

months_as_customer  age policy_bind_date policy_state policy_csl  \
0                   328   48       10/17/2014           OH    250/500   
1                   228   42        6/27/2006           IN    250/500   
2                   134   29         9/6/2000           OH    100/300   
3                   256   41        5/25/1990           IL    250/500   
4                   228   44         6/6/2014           IL   500/1000   
..                  ...  ...              ...          ...        ...   
995                   3   38        7/16/1991           OH   500/1000   
996                 285   41         1/5/2014           IL    100/300   
997                 130   34        2/17/2003           OH    250/500   
998                 458   62       11/18/2011           IL   500/1000   
999                 456   60       11/11/1996           OH    250/500   

     policy_deductable  policy_annual_premium  umbrella_limit  insured_zip  \
0                 1000                1406.91               0       466132   
1                 2000                1197.22         5000000       468176   
2                 2000                1413.14         5000000       430632   
3                 2000                1415.74         6000000       608117   
4                 1000                1583.91         6000000       610706   
..                 ...                    ...             ...          ...   
995               1000                1310.80               0       431289   
996               1000                1436.79               0       608177   
997                500                1383.49         3000000       442797   
998               2000                1356.92         5000000       441714   
999               1000                 766.19               0       612260   

    insured_sex  ... witnesses police_report_available total_claim_amount  \
0          MALE  ...         2                     YES              71610   
1          MALE  ...         0                       ?               5070   
2        FEMALE  ...         3                      NO              34650   
3        FEMALE  ...         2                      NO              63400   
4          MALE  ...         1                      NO               6500   
..          ...  ...       ...                     ...                ...   
995      FEMALE  ...         1                       ?              87200   
996      FEMALE  ...         3                       ?             108480   
997      FEMALE  ...         3                     YES              67500   
998        MALE  ...         1                     YES              46980   
999      FEMALE  ...         3                       ?               5060   

    injury_claim  property_claim  vehicle_claim   auto_make auto_model  \
0           6510           13020          52080        Saab        92x   
1            780             780           3510    Mercedes       E400   
2           7700            3850          23100       Dodge        RAM   
3           6340            6340          50720   Chevrolet      Tahoe   
4           1300             650           4550      Accura        RSX   
..           ...             ...            ...         ...        ...   
995        17440            8720          61040       Honda     Accord   
996        18080           18080          72320  Volkswagen     Passat   
997         7500            7500          52500      Suburu    Impreza   
998         5220            5220          36540        Audi         A5   
999          460             920           3680    Mercedes       E400   

    auto_year fraud_reported  
0        2004              Y  
1        2007              Y  
2        2007              N  
3        2014              Y  
4        2009              N  
..        ...            ...  
995      2006              N  
996      2015              N  
997      1996              N  
998      1998              N  
999      2007              N  

[100

In [40]:
## let's segregate the dependent and the independent variable 
X = df.drop('fraud_reported',axis=1)
y= df['fraud_reported']

In [41]:
X

months_as_customer  age policy_bind_date policy_state policy_csl  \
0                   328   48       10/17/2014           OH    250/500   
1                   228   42        6/27/2006           IN    250/500   
2                   134   29         9/6/2000           OH    100/300   
3                   256   41        5/25/1990           IL    250/500   
4                   228   44         6/6/2014           IL   500/1000   
..                  ...  ...              ...          ...        ...   
995                   3   38        7/16/1991           OH   500/1000   
996                 285   41         1/5/2014           IL    100/300   
997                 130   34        2/17/2003           OH    250/500   
998                 458   62       11/18/2011           IL   500/1000   
999                 456   60       11/11/1996           OH    250/500   

     policy_deductable  policy_annual_premium  umbrella_limit  insured_zip  \
0                 1000                1406.91               0       466132   
1                 2000                1197.22         5000000       468176   
2                 2000                1413.14         5000000       430632   
3                 2000                1415.74         6000000       608117   
4                 1000                1583.91         6000000       610706   
..                 ...                    ...             ...          ...   
995               1000                1310.80               0       431289   
996               1000                1436.79               0       608177   
997                500                1383.49         3000000       442797   
998               2000                1356.92         5000000       441714   
999               1000                 766.19               0       612260   

    insured_sex  ... bodily_injuries witnesses police_report_available  \
0          MALE  ...               1         2                     YES   
1          MALE  ...               0         0                       ?   
2        FEMALE  ...               2         3                      NO   
3        FEMALE  ...               1         2                      NO   
4          MALE  ...               0         1                      NO   
..          ...  ...             ...       ...                     ...   
995      FEMALE  ...               0         1                       ?   
996      FEMALE  ...               2         3                       ?   
997      FEMALE  ...               2         3                     YES   
998        MALE  ...               0         1                     YES   
999      FEMALE  ...               0         3                       ?   

    total_claim_amount  injury_claim  property_claim vehicle_claim  \
0                71610          6510           13020         52080   
1                 5070           780             780          3510   
2                34650          7700            3850         23100   
3                63400          6340            6340         50720   
4                 6500          1300             650          4550   
..                 ...           ...             ...           ...   
995              87200         17440            8720         61040   
996             108480         18080           18080         72320   
997              67500          7500            7500         52500   
998              46980          5220            5220         36540   
999               5060           460             920          3680   

      auto_make auto_model auto_year  
0          Saab        92x      2004  
1      Mercedes       E400      2007  
2         Dodge        RAM      2007  
3     Chevrolet      Tahoe      2014  
4        Accura        RSX      2009  
..          ...        ...       ...  
995       Honda     Accord      2006  
996  Volkswagen     Passat      2015  
997      Suburu    Impreza      1996  
998        Audi         A5      1998  
999    Mercedes       E400      

In [42]:
y

0      Y
1      Y
2      N
3      Y
4      N
      ..
995    N
996    N
997    N
998    N
999    N
Name: fraud_reported, Length: 1000, dtype: object

In [43]:
# Creating categorical and numerical columns 
categorical_cols= X.select_dtypes(include="object").columns
numerical_cols= X.select_dtypes(exclude="object").columns

In [44]:
categorical_cols

Index(['policy_bind_date', 'policy_state', 'policy_csl', 'insured_sex',
       'insured_education_level', 'insured_occupation', 'insured_hobbies',
       'insured_relationship', 'incident_date', 'incident_type',
       'collision_type', 'incident_severity', 'incident_state',
       'incident_city', 'incident_location', 'property_damage',
       'police_report_available', 'auto_make', 'auto_model'],
      dtype='object')

In [45]:
numerical_cols


Index(['months_as_customer', 'age', 'policy_deductable',
       'policy_annual_premium', 'umbrella_limit', 'insured_zip',
       'capital-gains', 'capital-loss', 'incident_hour_of_the_day',
       'number_of_vehicles_involved', 'bodily_injuries', 'witnesses',
       'total_claim_amount', 'injury_claim', 'property_claim', 'vehicle_claim',
       'auto_year'],
      dtype='object')

In [46]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

In [36]:
data = df.copy()

In [47]:
# Encode the categorical columns
encoder = LabelEncoder()

for cols in categorical_cols:
    X[cols] = encoder.fit_transform(X[cols])

In [48]:
X.head()

months_as_customer  age  policy_bind_date  policy_state  policy_csl  \
0                 328   48                99             2           1   
1                 228   42               684             1           1   
2                 134   29               945             2           0   
3                 256   41               604             0           1   
4                 228   44               705             0           2   

   policy_deductable  policy_annual_premium  umbrella_limit  insured_zip  \
0               1000                1406.91               0       466132   
1               2000                1197.22         5000000       468176   
2               2000                1413.14         5000000       430632   
3               2000                1415.74         6000000       608117   
4               1000                1583.91         6000000       610706   

   insured_sex  ...  bodily_injuries  witnesses  police_report_available  \
0            1  ...                1          2                        2   
1            1  ...                0          0                        0   
2            0  ...                2          3                        1   
3            0  ...                1          2                        1   
4            1  ...                0          1                        1   

   total_claim_amount  injury_claim  property_claim  vehicle_claim  auto_make  \
0               71610          6510           13020          52080         10   
1                5070           780             780           3510          8   
2               34650          7700            3850          23100          4   
3               63400          6340            6340          50720          3   
4                6500          1300             650           4550          0   

   auto_model  auto_year  
0           1       2004  
1          12       2007  
2          30       2007  
3          34       2014  
4          31       2009  

[5 rows x 36 columns]

In [50]:
# let's split the data into train -test data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [51]:
X_train 

months_as_customer  age  policy_bind_date  policy_state  policy_csl  \
29                  241   45               476             0           2   
535                  65   23               247             2           1   
695                 289   45               131             2           1   
557                  63   26                87             0           2   
836                 257   43               590             1           0   
..                  ...  ...               ...           ...         ...   
106                 464   61               149             2           2   
270                 369   55               507             2           1   
860                 230   42               178             1           0   
435                 102   28               849             2           1   
102                 279   41               702             0           1   

     policy_deductable  policy_annual_premium  umbrella_limit  insured_zip  \
29                2000                1104.50               0       432211   
535               1000                1099.95               0       473109   
695               2000                1221.41               0       466289   
557                500                1500.04         6000000       613826   
836               1000                 974.84               0       468984   
..                 ...                    ...             ...          ...   
106               1000                1125.37               0       604450   
270               2000                1589.54               0       444734   
860               1000                1023.11               0       476130   
435                500                1075.41               0       445648   
102                500                1497.35               0       460742   

     insured_sex  ...  bodily_injuries  witnesses  police_report_available  \
29             0  ...                2          2                        1   
535            0  ...                1          0                        2   
695            0  ...                2          1                        1   
557            1  ...                0          2                        2   
836            0  ...                0          1                        2   
..           ...  ...              ...        ...                      ...   
106            0  ...                0          2                        2   
270            1  ...                2          0                        2   
860            0  ...                1          2                        2   
435            1  ...                1          0                        1   
102            0  ...                2          3                        1   

     total_claim_amount  injury_claim  property_claim  vehicle_claim  \
29                91650         14100           14100          63450   
535               52400          6550            6550          39300   
695                2700           300             300           2100   
557                5160           860             860           3440   
836               85320         21330            7110          56880   
..                  ...           ...             ...            ...   
106               79800          6650           19950          53200   
270               85300         17060            8530          59710   
860               58850         10700           10700          37450   
435               73400          7340            7340          58720   
102               28800             0            3600          25200   

     auto_make  auto_model  auto_year  
29           0          33       2011  
535          0          23       2005  
695          6           6       2006  
557          0          33       2004  
836          9          29       2006  
..         ...         ...        ...  
106         10           3       2000  
270         12          18       

In [52]:
# let's now scale the numerical columns

from sklearn.preprocessing import StandardScaler


In [54]:
scaler = StandardScaler()


In [55]:
X_train = scaler.fit_transform(X_train)

In [56]:
X_train

array([[ 0.30141859,  0.64266744, -0.01564268, ..., -1.60219405,
         1.23443735,  1.00849147],
       [-1.24319263, -1.78353311, -0.83818555, ..., -1.60219405,
         0.33091505,  0.00771432],
       [ 0.7226762 ,  0.64266744, -1.25484482, ..., -0.13257214,
        -1.20507288,  0.17451051],
       ...,
       [ 0.20488039,  0.31182191, -1.08602598, ..., -1.60219405,
         0.33091505, -0.99306282],
       [-0.91847322, -1.2321239 ,  1.32413239, ..., -0.62244611,
         0.69232397, -1.49345139],
       [ 0.6349142 ,  0.20154007,  0.79612452, ..., -0.37750913,
        -0.30155057,  1.34208385]])

In [57]:
# We do not fit the scaler into test dataset so that while running the machine learning model, the model can only take the value of mean and standard deviation from the training dataset to restrict data leakage

X_test= scaler.transform(X_test)

In [58]:
X_test

array([[-1.76976464, -1.45268758,  1.01163793, ..., -1.35725706,
        -1.29542511, -0.32587806],
       [-0.40945362, -0.68071468, -0.25629933, ...,  0.60223881,
         0.87302843,  0.17451051],
       [ 1.56519141,  1.3043585 ,  0.93980013, ...,  1.09211278,
         0.15021058,  0.3413067 ],
       ...,
       [ 1.19659101,  0.97351297, -0.94594226, ...,  0.35730183,
        -1.11472065, -0.32587806],
       [-1.15543063, -1.34240574,  1.37082696, ...,  1.58198675,
         0.7826762 , -0.32587806],
       [-0.11106281, -0.01902362,  0.41897604, ...,  0.84717579,
        -1.47612957, -0.15908187]])

In [59]:
from sklearn.linear_model import LogisticRegression

In [60]:
Logistic= LogisticRegression()

In [61]:
Logistic.fit(X_train,y_train)

LogisticRegression()

In [62]:
Logistic.coef_

array([[ 3.37145690e-02, -3.69120871e-02, -9.01463914e-02,
         6.30595535e-02, -7.18365241e-02,  9.58556010e-02,
        -5.28238685e-02,  2.94895884e-01, -2.36945046e-03,
         1.31214188e-01,  7.65274704e-02, -5.84353932e-02,
        -1.09666637e-01, -2.90114372e-02, -7.78288625e-02,
        -4.96481856e-02,  1.39275852e-04,  2.67453375e-02,
        -5.75738442e-02, -1.32497915e+00, -7.14443822e-02,
        -1.72220489e-01, -6.97652377e-02,  3.05869020e-02,
        -7.40699156e-02,  8.79570272e-04,  9.28650545e-02,
         7.06806850e-02, -3.78271529e-02,  1.00755048e-01,
        -2.53279881e-01,  5.77407487e-02,  1.91946926e-01,
         3.98426533e-02, -1.16460982e-01, -4.73209909e-02]])

In [63]:
# prediction 
y_pred = Logistic.predict(X_test)

In [64]:
# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

Accuracy: 0.70


In [66]:
# Create confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(conf_matrix)

Confusion Matrix:
[[128  17]
 [ 42  13]]


In [68]:
# Display classification report
class_report = classification_report(y_test, y_pred)
print("Classification Report:")
print(class_report)

Classification Report:
              precision    recall  f1-score   support

           N       0.75      0.88      0.81       145
           Y       0.43      0.24      0.31        55

    accuracy                           0.70       200
   macro avg       0.59      0.56      0.56       200
weighted avg       0.67      0.70      0.67       200



In [69]:
model = DecisionTreeClassifier()
model.fit(X_train, y_train)

DecisionTreeClassifier()

In [70]:
# Make predictions
y_pred = model.predict(X_test)


In [72]:
# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

Accuracy: 0.73


In [74]:
# Create confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(conf_matrix)




Confusion Matrix:
[[120  25]
 [ 28  27]]


In [75]:
# Display classification report
class_report = classification_report(y_test, y_pred)
print("Classification Report:")
print(class_report)

Classification Report:
              precision    recall  f1-score   support

           N       0.81      0.83      0.82       145
           Y       0.52      0.49      0.50        55

    accuracy                           0.73       200
   macro avg       0.67      0.66      0.66       200
weighted avg       0.73      0.73      0.73       200



In [76]:
model = RandomForestClassifier()

In [77]:
model.fit(X_train, y_train)

RandomForestClassifier()

In [78]:
y_pred= model.predict(X_test)

In [79]:
# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

Accuracy: 0.74


In [80]:
# Create confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(conf_matrix)


Confusion Matrix:
[[129  16]
 [ 35  20]]


In [81]:
# Display classification report
class_report = classification_report(y_test, y_pred)
print("Classification Report:")
print(class_report)

Classification Report:
              precision    recall  f1-score   support

           N       0.79      0.89      0.83       145
           Y       0.56      0.36      0.44        55

    accuracy                           0.74       200
   macro avg       0.67      0.63      0.64       200
weighted avg       0.72      0.74      0.73       200



In [116]:
from sklearn.model_selection import GridSearchCV


In [117]:
# Initialize and train the AdaBoostClassifier
base_model = DecisionTreeClassifier(max_depth=5, random_state=42)  # Use a simple base classifier
model = AdaBoostClassifier(base_model)  # You can adjust n_estimators
# Define the grid of hyperparameters to search
param_grid = {
    'n_estimators': [50, 100, 150],
    'learning_rate': [0.01, 0.1, 1.0]
}

# Initialize GridSearchCV
grid_search = GridSearchCV(model, param_grid, cv=3, scoring='accuracy')

# Fit the grid search to your data
grid_search.fit(X_train, y_train)

# Print the best hyperparameters
print("Best Hyperparameters:", grid_search.best_params_)

# Get the best model
best_model = grid_search.best_estimator_

# Make predictions using the best model
predictions = best_model.predict(X_test)

Best Hyperparameters: {'learning_rate': 0.01, 'n_estimators': 100}


In [118]:
# # Make predictions
# predictions = model.predict(X_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, predictions)
print(f"Accuracy: {accuracy:.2f}")


Accuracy: 0.80


In [119]:
# Create confusion matrix
conf_matrix = confusion_matrix(y_test, predictions)
print("Confusion Matrix:")
print(conf_matrix)

Confusion Matrix:
[[121  24]
 [ 17  38]]


In [120]:
# Display classification report
class_report = classification_report(y_test, predictions)
print("Classification Report:")
print(class_report)

Classification Report:
              precision    recall  f1-score   support

           N       0.88      0.83      0.86       145
           Y       0.61      0.69      0.65        55

    accuracy                           0.80       200
   macro avg       0.74      0.76      0.75       200
weighted avg       0.80      0.80      0.80       200

